=== blacktunes/hiiro-button/schema/voice.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "title": "语音名"
      },
      "path": {
        "type": "string",
        "title": "文件名",
        "pattern": "[^*|\\:\"<>?/]+\\.(mp3|wav)+"
      },
      "date": {
        "type": "string",
        "title": "更新时间",
        "format": "date"
      },
      "translate": {
        "type": "object",
        "title": "翻译",
        "properties": {
          "zh-CN": {
            "type": "string",
            "title": "中文翻译"
          },
          "en-US": {
            "type": "string",
            "title": "英文翻译"
          }
        }
      },
      "category": {
        "type": "string",
        "title": "语音分类"
      },
      "mark": {
        "type": "object",
        "title": "语音来源",
        "properties": {
          "title": {
            "type": "string",
            "title": "来源标题"
          },
          "time": {
            "type": "string",
            "title": "所在时间",
            "pattern": "^[0-9]+(\\:[0-6][0-9]){1,2}~[0-9]+(\\:[0-6][0-9]){1,2}$"
          },
          "url": {
            "type": "string",
            "title": "来源地址"
          }
        }
      }
    },
    "required": [
      "name",
      "path",
      "date",
      "translate",
      "category"
    ]
  }
}

=== blacktunes/hiiro-button/setting/translate/12_2023_04_18.json
[
  {
    "name": "切~垃圾",
    "path": "切~垃圾.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "切~垃圾",
      "en-US": "切~垃圾"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "有个hentai！9me！",
    "path": "有个hentai！9me！.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "有个hentai！9me！",
      "en-US": "有个hentai！9me！"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "hiihiihii",
    "path": "hiihiihii.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "hiihiihii",
      "en-US": "hiihiihii"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "my欧派真的有点大",
    "path": "my欧派真的有点大.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "my欧派真的有点大",
      "en-US": "my欧派真的有点大"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "这个真的有点大",
    "path": "这个真的有点大.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "这个真的有点大",
      "en-US": "这个真的有点大"
    },
    "category": "混沌",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "不要~~",
    "path": "不要~~.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "不要~~",
      "en-US": "不要~~"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "你这个！",
    "path": "你这个！.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "你这个！",
      "en-US": "你这个！"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "去love hotel",
    "path": "去love hotel.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "去love hotel",
      "en-US": "去love hotel"
    },
    "category": "混沌",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "哎呀宝贝儿",
    "path": "哎呀宝贝儿.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "哎呀宝贝儿",
      "en-US": "哎呀宝贝儿"
    },
    "category": "混沌",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "哈斯哈斯",
    "path": "哈斯哈斯.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "哈斯哈斯",
      "en-US": "哈斯哈斯"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "呼~",
    "path": "呼~.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "呼~",
      "en-US": "呼~"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "好热啊",
    "path": "好热啊.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "好热啊",
      "en-US": "好热啊"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "好的主人",
    "path": "好的主人.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "好的主人",
      "en-US": "好的主人"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "安静安静",
    "path": "安静安静.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "安静安静",
      "en-US": "安静安静"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "别说话了你个八嘎",
    "path": "别说话了你个八嘎.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "别说话了你个八嘎",
      "en-US": "别说话了你个八嘎"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "很好很好很好",
    "path": "很好很好很好.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "很好很好很好",
      "en-US": "很好很好很好"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "我爱王牛奶",
    "path": "我爱王牛奶.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "我爱王牛奶",
      "en-US": "我爱王牛奶"
    },
    "category": "名言",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "为~什~么~",
    "path": "为~什~么~.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "为~什~么~",
      "en-US": "为~什~么~"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "我的老公去哪里了",
    "path": "我的老公去哪里了.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "我的老公去哪里了",
      "en-US": "我的老公去哪里了"
    },
    "category": "名言",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "哇我真牛逼啊",
    "path": "哇我真牛逼啊.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "哇我真牛逼啊",
      "en-US": "哇我真牛逼啊"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "滋~~~~崩",
    "path": "滋~~~~崩.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "滋~~~~崩",
      "en-US": "滋~~~~崩"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "爹！",
    "path": "爹！.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "爹！",
      "en-US": "爹！"
    },
    "category": "混沌",
    "mark": {
      "title": "群友投稿2"
    }
  },
  {
    "name": "苏卡不列",
    "path": "苏卡不列.mp3",
    "date": "2023-4-18",
    "translate": {
      "zh-CN": "苏卡不列",
      "en-US": "苏卡不列"
    },
    "category": "混沌",
    "mark": {
      "title": "群友投稿2"
    }
  }
]

=== blacktunes/hiiro-button/setting/translate/06_2021_11_02.json
[
  {
    "name": "咚咚咚",
    "path": "咚咚咚.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "咚咚咚",
      "en-US": "Dong Dong Dong"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】10.28 Thu. 聊天",
      "time": "11:21~11:25",
      "url": "https://www.bilibili.com/video/BV1uU4y1c7pr"
    }
  },
  {
    "name": "民娜我是你爸爸2",
    "path": "民娜我是你爸爸2.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "民娜我是你爸爸2",
      "en-US": "I'm your Baba 2"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】10.28 Thu. 聊天",
      "time": "54:50~54:52",
      "url": "https://www.bilibili.com/video/BV1uU4y1c7pr"
    }
  },
  {
    "name": "民娜我是你爸爸3",
    "path": "民娜我是你爸爸3.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "民娜我是你爸爸3",
      "en-US": "I'm your Baba 3"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】10.28 Thu. 聊天",
      "time": "54:56~54:58",
      "url": "https://www.bilibili.com/video/BV1uU4y1c7pr"
    }
  },
  {
    "name": "no~~~~~",
    "path": "no~~~~~.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "no~~~~~",
      "en-US": "no~~~~~"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】10.31 Sun. 万圣节快乐！聊天+看三国",
      "time": "1:16:13~1:16:16",
      "url": "https://www.bilibili.com/video/BV1Eq4y1V7ae"
    }
  },
  {
    "name": "巧克力",
    "path": "巧克力.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "抱抱~亲亲~mua~",
      "en-US": "Hug ~ kiss ~ MUA~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】10.31 Sun. 万圣节快乐！聊天+看三国",
      "time": "1:15:26~1:15:37",
      "url": "https://www.bilibili.com/video/BV1Eq4y1V7ae"
    }
  },
  {
    "name": "生日歌",
    "path": "生日歌.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "生日歌",
      "en-US": "Birthday"
    },
    "category": "唱歌",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "16:15~16:21",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "为什么你们这么快啊",
    "path": "为什么你们这么快啊.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "为什么你们这么快啊",
      "en-US": "Why are you so fast"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "35:26~35:27",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "bubububububu",
    "path": "bubububububu.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "bubububububu",
      "en-US": "bubububububu"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "50:10~50:12",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "王牛奶们~",
    "path": "王牛奶们~.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "王牛奶们~",
      "en-US": "Wang milk~"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:03:53~3:03:56",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "你们是我的老公",
    "path": "你们是我的老公.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "你们是我的老公",
      "en-US": "You are my husband"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:03:58~3:04:05",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "笑12",
    "path": "笑12.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "笑",
      "en-US": "Laugh"
    },
    "category": "混沌",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:04:05~3:04:07",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "王牛奶是谁啊",
    "path": "王牛奶是谁啊.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "王牛奶是谁啊",
      "en-US": "Who is Wang milk"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:04:11~3:04:12",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "笑13",
    "path": "笑13.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "笑",
      "en-US": "Laugh"
    },
    "category": "混沌",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:04:12~3:04:14",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "mua~",
    "path": "mua~.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "mua~",
      "en-US": "mua~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:04:50~3:04:51",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "mua~2",
    "path": "mua~2.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "mua~",
      "en-US": "mua~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:05:04~3:05:05",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "mua~3",
    "path": "mua~3.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "mua~",
      "en-US": "mua~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:07:03~3:07:04",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "mua~4",
    "path": "mua~4.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "mua~",
      "en-US": "mua~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:07:20~3:07:21",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "爱你",
    "path": "爱你.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "爱你",
      "en-US": "love you"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:08:03~3:08:04",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "mua~5",
    "path": "mua~5.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "mua~",
      "en-US": "mua~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:08:07~3:08:08",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "王酸奶们~",
    "path": "王酸奶们~.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "王酸奶们~",
      "en-US": "Wang yogurt~"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:08:46~3:08:48",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "下次加油啊",
    "path": "下次加油啊.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "下次加油啊",
      "en-US": "下次加油啊"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:08:56~3:08:57",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "王酸奶们mua~",
    "path": "王酸奶们mua~.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "王酸奶们mua~",
      "en-US": "Wang yogurt mua~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:09:16~3:09:19",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  },
  {
    "name": "王牛奶们晚安",
    "path": "王牛奶们晚安.mp3",
    "date": "2021-11-03",
    "translate": {
      "zh-CN": "王牛奶们晚安",
      "en-US": "Good night, Wang milk"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】11.02 Tue. 聊天+牛奶房间vs酸奶房间",
      "time": "3:09:20~3:09:21",
      "url": "https://www.bilibili.com/video/BV143411k7u9"
    }
  }
]
