=== blacktunes/hiiro-button/schema/voice.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "title": "语音名"
      },
      "path": {
        "type": "string",
        "title": "文件名",
        "pattern": "[^*|\\:\"<>?/]+\\.(mp3|wav)+"
      },
      "date": {
        "type": "string",
        "title": "更新时间",
        "format": "date"
      },
      "translate": {
        "type": "object",
        "title": "翻译",
        "properties": {
          "zh-CN": {
            "type": "string",
            "title": "中文翻译"
          },
          "en-US": {
            "type": "string",
            "title": "英文翻译"
          }
        }
      },
      "category": {
        "type": "string",
        "title": "语音分类"
      },
      "mark": {
        "type": "object",
        "title": "语音来源",
        "properties": {
          "title": {
            "type": "string",
            "title": "来源标题"
          },
          "time": {
            "type": "string",
            "title": "所在时间",
            "pattern": "^[0-9]+(\\:[0-6][0-9]){1,2}~[0-9]+(\\:[0-6][0-9]){1,2}$"
          },
          "url": {
            "type": "string",
            "title": "来源地址"
          }
        }
      }
    },
    "required": [
      "name",
      "path",
      "date",
      "translate",
      "category"
    ]
  }
}

=== blacktunes/hiiro-button/setting/translate/11_2022_12_26.json
[
  {
    "name": "一个好色声音",
    "path": "一个好色声音.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "一个好色声音",
      "en-US": "一个好色声音"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "我是wife",
    "path": "我是wife.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "我是wife",
      "en-US": "我是wife"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "谢谢你",
    "path": "谢谢你.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "谢谢你",
      "en-US": "谢谢你"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "爱老虎油1",
    "path": "爱老虎油1.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "爱老虎油",
      "en-US": "爱老虎油"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "爱老虎油2",
    "path": "爱老虎油2.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "爱老虎油",
      "en-US": "爱老虎油"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "爸爸跟孩子不会结婚",
    "path": "爸爸跟孩子不会结婚.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "爸爸跟孩子不会结婚",
      "en-US": "爸爸跟孩子不会结婚"
    },
    "category": "名言",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "mother 哔——",
    "path": "mother 哔——.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "mother 哔——",
      "en-US": "mother 哔——"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "mother fa——",
    "path": "mother fa——.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "mother fa——",
      "en-US": "mother fa——"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "son of 哔——",
    "path": "son of 哔——.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "son of 哔——",
      "en-US": "son of 哔——"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "阿姨洗铁路1",
    "path": "阿姨洗铁路1.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "阿姨洗铁路",
      "en-US": "阿姨洗铁路"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "你是什么笨蛋呀",
    "path": "你是什么笨蛋呀.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "你是什么笨蛋呀",
      "en-US": "你是什么笨蛋呀"
    },
    "category": "名言",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "呃呃呃别",
    "path": "呃呃呃别.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "呃呃呃别",
      "en-US": "呃呃呃别"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "钉宫三连",
    "path": "钉宫三连.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "钉宫三连",
      "en-US": "钉宫三连"
    },
    "category": "幼猫",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "I love you too",
    "path": "I love you too.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "I love you too",
      "en-US": "I love you too"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "I love you too,mua~",
    "path": "I love you too,mua~.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "I love you too,mua~",
      "en-US": "I love you too,mua~"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "mua3",
    "path": "mua3.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "Um~mua~",
      "en-US": "Um~mua~"
    },
    "category": "mua",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "nya~",
    "path": "nya~.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "nya~",
      "en-US": "nya~"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "rua",
    "path": "rua.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "rua",
      "en-US": "rua"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "wow",
    "path": "wow.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "wow",
      "en-US": "wow"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "噗噗",
    "path": "噗噗.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "噗噗",
      "en-US": "噗噗"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "喵~2",
    "path": "喵~2.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "喵~",
      "en-US": "喵~"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "抱抱亲亲mua",
    "path": "抱抱亲亲mua.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "抱抱亲亲mua",
      "en-US": "抱抱亲亲mua"
    },
    "category": "mua",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "王牛奶骂我呀",
    "path": "王牛奶骂我呀.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "王牛奶骂我呀",
      "en-US": "王牛奶骂我呀"
    },
    "category": "名言",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "钉宫三连2",
    "path": "钉宫三连2.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "钉宫三连",
      "en-US": "钉宫三连"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "我的爸爸告诉我",
    "path": "我的爸爸告诉我.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "我的爸爸告诉我",
      "en-US": "我的爸爸告诉我"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "啊~2",
    "path": "啊~2.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "啊~",
      "en-US": "啊~"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "没事",
    "path": "没事.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "没事",
      "en-US": "没事"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "你谁啊",
    "path": "你谁啊.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "你谁啊",
      "en-US": "你谁啊"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "我害怕对不起对不起对不起",
    "path": "我害怕对不起对不起对不起.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "我害怕对不起对不起对不起",
      "en-US": "我害怕对不起对不起对不起"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "OK~1~2~3~",
    "path": "OK~1~2~3~.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "OK~1~2~3~",
      "en-US": "OK~1~2~3~"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "我们可以去约会吗",
    "path": "我们可以去约会吗.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "我们可以去约会吗",
      "en-US": "我们可以去约会吗"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "我想亲亲",
    "path": "我想亲亲.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "我想亲亲",
      "en-US": "我想亲亲"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "大家好我是粉色猫猫",
    "path": "大家好我是粉色猫猫.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "大家好我是粉色猫猫",
      "en-US": "大家好我是粉色猫猫"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "晚上好你们好啊",
    "path": "晚上好你们好啊.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "晚上好你们好啊",
      "en-US": "晚上好你们好啊"
    },
    "category": "日常",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "啊~~~2",
    "path": "啊~~~2.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "啊~~~",
      "en-US": "啊~~~"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "大概是在哭",
    "path": "大概是在哭.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "大概是在哭",
      "en-US": "大概是在哭"
    },
    "category": "糟糕",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "没有东西之歌",
    "path": "没有东西之歌.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "没有东西之歌",
      "en-US": "没有东西之歌"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "没问题之歌",
    "path": "没问题之歌.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "没问题之歌",
      "en-US": "没问题之歌"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  },
  {
    "name": "没问题之歌2",
    "path": "没问题之歌2.mp3",
    "date": "2022-12-26",
    "translate": {
      "zh-CN": "没问题之歌",
      "en-US": "没问题之歌"
    },
    "category": "可爱",
    "mark": {
      "title": "群友投稿1"
    }
  }
]

=== blacktunes/hiiro-button/setting/translate/07_2021_12_11.json
[
  {
    "name": "对不起哦",
    "path": "对不起哦.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "对不起哦",
      "en-US": "Sorry~"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "2:00~2:03",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "不要啊~",
    "path": "不要啊~.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "不要啊~",
      "en-US": "No~"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "42:37~42:39",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "王牛奶不要啊~",
    "path": "王牛奶不要啊~.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "王牛奶不要啊~",
      "en-US": "Wang Milk, No~"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "42:41~42:43",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "大姐姐suki",
    "path": "大姐姐suki.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "大姐姐suki",
      "en-US": "Big sister suki"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "46:25~46:26",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "生日歌2",
    "path": "生日歌2.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "生日歌2",
      "en-US": "Birthday 2"
    },
    "category": "唱歌",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "47:16~47:31",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "老公我好喜欢你啊~",
    "path": "老公我好喜欢你啊~.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "老公我好喜欢你啊~",
      "en-US": "Husband, I love you so much~"
    },
    "category": "mua",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "49:25~49:29",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "我是baka",
    "path": "我是baka.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "我是baka",
      "en-US": "I am baka"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "52:05~52:06",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "我是baka2",
    "path": "我是baka2.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "我是baka",
      "en-US": "I am baka"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "52:07~52:08",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "我也喜欢我自己的耳朵",
    "path": "我也喜欢我自己的耳朵.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "我也喜欢我自己的耳朵",
      "en-US": "I like my ears, too"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "54:48~54:50",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "可以让你的狗给我一个mua吗",
    "path": "可以让你的狗给我一个mua吗.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "可以让你的狗给我一个mua吗",
      "en-US": "Can your dog give me a mua"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "55:28~55:31",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "阿古巴",
    "path": "阿古巴.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "阿古巴",
      "en-US": "akuba"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "55:41~55:42",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "awsl4",
    "path": "awsl4.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "awsl",
      "en-US": "awsl"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "55:45~55:46",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "我的狗",
    "path": "我的狗.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "我的狗",
      "en-US": "My dog"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "55:33~55:40",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "你不看我吗",
    "path": "你不看我吗.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "你不看我吗",
      "en-US": "Won't you come to see me"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "57:50~57:57",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "喜欢我的耳朵吗",
    "path": "喜欢我的耳朵吗.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "喜欢我的耳朵吗",
      "en-US": "Do you like my ears"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "59:22~59:27",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "你为什么看别的女人",
    "path": "你为什么看别的女人.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "你为什么看别的女人",
      "en-US": "Why are you looking at other women"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "1:02:49~1:02:59",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "我难道不可爱吗(日)",
    "path": "我难道不可爱吗(日).mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "我难道不可爱吗(日)",
      "en-US": "Aren't I cute?(JP)"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "1:03:27~1:03:35",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "你为什么看别的女人(英)",
    "path": "你为什么看别的女人(英).mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "你为什么看别的女人(英)",
      "en-US": "Why are you looking at other women"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "1:04:54~1:05:06",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "我是一个很强的女人",
    "path": "我是一个很强的女人.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "我是一个很强的女人",
      "en-US": "I am a strong woman"
    },
    "category": "名言",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "1:28:31~1:28:35",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  },
  {
    "name": "晚安~拜拜~",
    "path": "晚安~拜拜~.mp3",
    "date": "2021-12-12",
    "translate": {
      "zh-CN": "晚安~拜拜~",
      "en-US": "Good night~ byebye~"
    },
    "category": "软猫",
    "mark": {
      "title": "【Hiiro Record】12.11 Sat. 这几天没聊太多 手机直播",
      "time": "1:28:31~1:28:35",
      "url": "https://www.bilibili.com/video/BV1a34y1974E"
    }
  }
]

=== blacktunes/hiiro-button/setting/translate/09_2021_05_18.json
[
  {
    "name": "别说了别说了别说了2",
    "path": "别说了别说了别说了2.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "别说了别说了别说了",
      "en-US": "Stop talking"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "11:21~11:24",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "阿里嘎多~",
    "path": "阿里嘎多~.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "阿里嘎多~",
      "en-US": "Thank you~"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "19:19~19:24",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "I am your girlfriend",
    "path": "I am your girlfriend.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "I am your girlfriend",
      "en-US": "I am your girlfriend"
    },
    "category": "清楚",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "37:53~37:54",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "健康的笑声",
    "path": "健康的笑声.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "健康的笑声",
      "en-US": "Healthy laughter"
    },
    "category": "混沌",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "57:10~57:35",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "健康的笑声2",
    "path": "健康的笑声2.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "健康的笑声",
      "en-US": "Healthy laughter"
    },
    "category": "混沌",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "57:41~57:49",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "三点几啦",
    "path": "三点几啦.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "三点几啦",
      "en-US": "三点几啦"
    },
    "category": "混沌",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:03:46~1:03:55",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "化物语绕口令",
    "path": "化物语绕口令.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "化物语绕口令",
      "en-US": "化物语绕口令"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:15:52~1:15:58",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "我是甜菜吗",
    "path": "我是甜菜吗.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "我是甜菜吗",
      "en-US": "Am I a genius?"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:16:03~1:16:04",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "化物语绕口令2",
    "path": "化物语绕口令2.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "化物语绕口令2",
      "en-US": "化物语绕口令2"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:16:36~1:16:42",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "化物语绕口令3",
    "path": "化物语绕口令3.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "化物语绕口令3",
      "en-US": "化物语绕口令3"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:16:49~1:16:55",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "reoreoreo",
    "path": "reoreoreo.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "reoreoreo",
      "en-US": "reoreoreo"
    },
    "category": "混沌",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:19:16~1:19:18",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "开水3",
    "path": "开水3.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "开水",
      "en-US": "Boiling Water"
    },
    "category": "烧开水",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:19:19~1:19:20",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "不学不学",
    "path": "不学不学.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "不学不学",
      "en-US": "No Learning No Learning"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:20:58~1:21:00",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "欢迎回家❤",
    "path": "欢迎回家❤.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "欢迎回家❤",
      "en-US": "Welcome Home❤"
    },
    "category": "清楚",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:24:04~1:24:13",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "大姐姐老婆role play",
    "path": "大姐姐老婆role play.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "大姐姐老婆role play",
      "en-US": "wife role play"
    },
    "category": "清楚",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:26:32~1:26:40",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "拜拜~",
    "path": "拜拜~.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "拜拜~",
      "en-US": "Bye-bye~"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:26:47~1:26:48",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "打咩desu",
    "path": "打咩desu.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "打咩desu",
      "en-US": "da mie desu"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:27:09~1:27:13",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "呜呜呜~",
    "path": "呜呜呜~.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "呜呜呜~",
      "en-US": "wuwuwu~"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:27:15~1:27:17",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "萝莉老婆role play",
    "path": "萝莉老婆role play.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "萝莉老婆role play",
      "en-US": "loli wife role play"
    },
    "category": "清楚",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:29:34~1:29:42",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "FBI!",
    "path": "FBI!.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "FBI!",
      "en-US": "FBI!"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:30:16~1:30:18",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "完了完了",
    "path": "完了完了.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "完了完了",
      "en-US": "It's over. It's over."
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:30:36~1:30:37",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "惠惠",
    "path": "惠惠.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "惠惠",
      "en-US": "Megumin"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:36:39~1:36:47",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "Explosion",
    "path": "Explosion.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "Explosion",
      "en-US": "Explosion"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:36:54~1:36:56",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "bakuretsu lalala",
    "path": "bakuretsu lalala.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "bakuretsu lalala",
      "en-US": "bakuretsu lalala"
    },
    "category": "可爱",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:36:58~1:37:03",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "你们真的有问题",
    "path": "你们真的有问题.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "你们真的有问题",
      "en-US": "You really have a problem."
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:40:37~1:40:38",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "Old McDonald Had A Farm",
    "path": "Old McDonald Had A Farm.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "Old McDonald Had A Farm",
      "en-US": "Old McDonald Had A Farm"
    },
    "category": "唱歌",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:42:57~1:43:09",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  },
  {
    "name": "ABCDEFG",
    "path": "ABCDEFG.mp3",
    "date": "2022-03-17",
    "translate": {
      "zh-CN": "ABCDEFG",
      "en-US": "ABCDEFG"
    },
    "category": "唱歌",
    "mark": {
      "title": "【Hiiro Record】5.18 Tue. 老角色扮演了",
      "time": "1:43:18~1:43:23",
      "url": "https://www.bilibili.com/video/BV14V411j7nN"
    }
  }
]

=== blacktunes/hiiro-button/setting/translate/05_2021_04_04.json
[
  {
    "name": "我好困啊",
    "path": "我好困啊.mp3",
    "date": "2021-04-06",
    "translate": {
      "zh-CN": "我好困啊",
      "en-US": "I am so sleepy"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】4.04 Sun. 学中文 & 听中文儿歌！",
      "time": "3:10~3:14",
      "url": "https://www.bilibili.com/video/BV1BV411n7nr"
    }
  },
  {
    "name": "太可爱了",
    "path": "太可爱了.mp3",
    "date": "2021-04-06",
    "translate": {
      "zh-CN": "太可爱了",
      "en-US": "It's so cute"
    },
    "category": "日常",
    "mark": {
      "title": "【Hiiro Record】4.04 Sun. 学中文 & 听中文儿歌！",
      "time": "6:12~6:15",
      "url": "https://www.bilibili.com/video/BV1BV411n7nr"
    }
  },
  {
    "name": "呀咩嗲2",
    "path": "呀咩嗲2.mp3",
    "date": "2021-04-06",
    "translate": {
      "zh-CN": "呀咩嗲",
      "en-US": "yamiedie"
    },
    "category": "软猫",
    "mark": {
      "title": "【Hiiro Record】4.04 Sun. 学中文 & 听中文儿歌！",
      "time": "15:58~15:59",
      "url": "https://www.bilibili.com/video/BV1BV411n7nr"
    }
  },
  {
    "name": "无路赛2",
    "path": "无路赛2.mp3",
    "date": "2021-04-06",
    "translate": {
      "zh-CN": "无路赛",
      "en-US": "Urusai"
    },
    "category": "软猫",
    "mark": {
      "title": "【Hiiro Record】4.04 Sun. 学中文 & 听中文儿歌！",
      "time": "15:59~16:00",
      "url": "https://www.bilibili.com/video/BV1BV411n7nr"
    }
  },
  {
    "name": "NB啊",
    "path": "NB啊.mp3",
    "date": "2021-04-06",
    "translate": {
      "zh-CN": "NB啊",
      "en-US": "Niubility"
    },
    "category": "混沌",
    "mark": {
      "title": "【Hiiro Record】4.04 Sun. 学中文 & 听中文儿歌！",
      "time": "26:29~26:30",
      "url": "https://www.bilibili.com/video/BV1BV411n7nr"
    }
  }
]
